version: '2'
services:

  luigid:
    image: winery/orchestrator:latest
    build:
      context: ./orchestrator
    command: luigid
    ports:
      - "8082:8082"

  orchestrator:
    image: winery/orchestrator:latest
    depends_on:
      - luigid
    environment:
      - PROJECT_ROOT=$PWD
      - PIPELINE_VERSION=2
      - ORCHESTRATOR_NETWORK=winery_default
    volumes:
      - ./data_root:/usr/share/data/ # Mount data directory
      - /var/run/docker.sock:/var/run/docker.sock # Mount docker socket
      - ./orchestrator:/opt/orchestrator # Mount code for faster development
    build:
      context: ./orchestrator
    command: luigi --module task PredictModel --scheduler-host luigid
